DEBUG 2015-09-24 01:44:40,567: 	 Executing command: 'submit'
DEBUG 2015-09-24 01:44:40,568: 	 Found CRAB cache file /afs/cern.ch/user/d/dromeroa/.crab3
DEBUG 2015-09-24 01:44:40,579: 	 Checking credentials
DEBUG 2015-09-24 01:44:40,580: 	 Found proxy file /tmp/x509up_u47670
DEBUG 2015-09-24 01:44:40,580: 	 Getting proxy life time left
DEBUG 2015-09-24 01:44:41,184: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u47670 -timeleft
 output : 601644

 error: 
 retcode : 0
DEBUG 2015-09-24 01:44:41,690: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u47670 -actimeleft
 output : 601644

 error: 
 retcode : 0
DEBUG 2015-09-24 01:44:41,690: 	 Proxy valid for 167:07:24 hours
INFO 2015-09-24 01:44:41,691: 	 Will use CRAB configuration file crabConfig_EDBR_analysis.py
DEBUG 2015-09-24 01:44:41,691: 	 Loading CRAB configuration file.
DEBUG 2015-09-24 01:44:41,732: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2015-09-24 01:44:41,732: 	 Working area '/afs/cern.ch/work/d/dromeroa/private/EDBR_CRAB3_SEP22/CMSSW_7_4_11_patch1/src/ExoDiBosonResonances/EDBRTreeMaker/test/EDBR_crab_projects/crab_EDBR_ZJetsToNuNu_HT-200To400_25ns' already exists 
Please change the requestName in the config file
ERROR 2015-09-24 01:44:41,732: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1509/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1509/bin/crab", line 137, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1509/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 38, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1509/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 300, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1509/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/d/dromeroa/private/EDBR_CRAB3_SEP22/CMSSW_7_4_11_patch1/src/ExoDiBosonResonances/EDBRTreeMaker/test/EDBR_crab_projects/crab_EDBR_ZJetsToNuNu_HT-200To400_25ns' already exists 
Please change the requestName in the config file
